export default (app) => {
  app.post(
    `/tenant/:tenantId/machine`,
    require('./machineCreate').default,
  );
  app.put(
    `/tenant/:tenantId/machine/:id`,
    require('./machineUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/machine/import`,
    require('./machineImport').default,
  );
  app.delete(
    `/tenant/:tenantId/machine`,
    require('./machineDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/machine/autocomplete`,
    require('./machineAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/machine/autocomplete-site`,
    require('./machineAutocompleteBySite').default,
  );
  app.get(
    `/tenant/:tenantId/machine/autocomplete-siteCollab`,
    require('./machineAutocompleteBySiteCollab').default,
  );
  app.get(
    `/tenant/:tenantId/machine`,
    require('./machineList').default,
  );
  app.get(
    `/tenant/:tenantId/machine-site`,
    require('./machineListBySite').default,
  );
  app.get(
    `/tenant/:tenantId/machine/:id`,
    require('./machineFind').default,
  );
};
